//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HealthDemo {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HealthDemo.AppResources", typeof(AppResources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Al Ain Hospital, a highly specialized acute care and emergency hospital with 402 beds and more than 35 medical departments and divisions, is one of two major hospitals in the AI Ain region of the Emirate of Abu Dhabi belonging to the health system of the Abu Dhabi Health Services Company SEHA (www.seha.ae).
        /// </summary>
        internal static string About_Content {
            get {
                return ResourceManager.GetString("About_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About us.
        /// </summary>
        internal static string About_HeaderTitle {
            get {
                return ResourceManager.GetString("About_HeaderTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clinical.
        /// </summary>
        internal static string Appointment_FORM_Clinical {
            get {
                return ResourceManager.GetString("Appointment_FORM_Clinical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string Appointment_FORM_Email {
            get {
                return ResourceManager.GetString("Appointment_FORM_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note:.
        /// </summary>
        internal static string Appointment_FORM_Head {
            get {
                return ResourceManager.GetString("Appointment_FORM_Head", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID.
        /// </summary>
        internal static string Appointment_FORM_ID {
            get {
                return ResourceManager.GetString("Appointment_FORM_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MRN.
        /// </summary>
        internal static string Appointment_FORM_MRN {
            get {
                return ResourceManager.GetString("Appointment_FORM_MRN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string Appointment_FORM_Name {
            get {
                return ResourceManager.GetString("Appointment_FORM_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        internal static string Appointment_FORM_Phone {
            get {
                return ResourceManager.GetString("Appointment_FORM_Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Referral Reference.
        /// </summary>
        internal static string Appointment_FORM_Referral {
            get {
                return ResourceManager.GetString("Appointment_FORM_Referral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        internal static string Appointment_FORM_Submit {
            get {
                return ResourceManager.GetString("Appointment_FORM_Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thiqa.
        /// </summary>
        internal static string Appointment_FORM_Thiqa {
            get {
                return ResourceManager.GetString("Appointment_FORM_Thiqa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please fill the form.
        /// </summary>
        internal static string Appointment_SEND_DLG_Msg {
            get {
                return ResourceManager.GetString("Appointment_SEND_DLG_Msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you for submitting your request, you will be contracted shortly.
        /// </summary>
        internal static string Appointment_SUBMIT_DLG_Msg {
            get {
                return ResourceManager.GetString("Appointment_SUBMIT_DLG_Msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request has been sent!.
        /// </summary>
        internal static string Appointment_SUBMIT_DLG_Title {
            get {
                return ResourceManager.GetString("Appointment_SUBMIT_DLG_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appointment.
        /// </summary>
        internal static string Appointment_Title {
            get {
                return ResourceManager.GetString("Appointment_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        internal static string AppointmentResult_Date {
            get {
                return ResourceManager.GetString("AppointmentResult_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time.
        /// </summary>
        internal static string AppointmentResult_Time {
            get {
                return ResourceManager.GetString("AppointmentResult_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calendar.
        /// </summary>
        internal static string Calendar_Title {
            get {
                return ResourceManager.GetString("Calendar_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categories.
        /// </summary>
        internal static string Category_Title {
            get {
                return ResourceManager.GetString("Category_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credit Hour:.
        /// </summary>
        internal static string CME_CreditHour {
            get {
                return ResourceManager.GetString("CME_CreditHour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description:.
        /// </summary>
        internal static string CME_Description {
            get {
                return ResourceManager.GetString("CME_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time and Date:.
        /// </summary>
        internal static string CME_DT {
            get {
                return ResourceManager.GetString("CME_DT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CME.
        /// </summary>
        internal static string CME_Head {
            get {
                return ResourceManager.GetString("CME_Head", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        internal static string CME_Register {
            get {
                return ResourceManager.GetString("CME_Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please fill the form.
        /// </summary>
        internal static string Cme_REGISTER_DLG_Msg {
            get {
                return ResourceManager.GetString("Cme_REGISTER_DLG_Msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speaker:.
        /// </summary>
        internal static string CME_Speaker {
            get {
                return ResourceManager.GetString("CME_Speaker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title:.
        /// </summary>
        internal static string CME_Title {
            get {
                return ResourceManager.GetString("CME_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Venue:.
        /// </summary>
        internal static string CME_Venue {
            get {
                return ResourceManager.GetString("CME_Venue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AAH Ambulance:.
        /// </summary>
        internal static string Contact_Ambulance {
            get {
                return ResourceManager.GetString("Contact_Ambulance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AAH Call center:.
        /// </summary>
        internal static string Contact_CallCenter {
            get {
                return ResourceManager.GetString("Contact_CallCenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Al Ain Hospital, a highly specialized acute care and emergency hospital with 402 beds and more than 35 medical departments and divisions, is one of two major hospitals in the AI Ain region of the Emirate of Abu Dhabi belonging to the health system of the Abu Dhabi Health Services Company SEHA (www.seha.ae).
        /// </summary>
        internal static string Contact_Content {
            get {
                return ResourceManager.GetString("Contact_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Important Phone Numbers.
        /// </summary>
        internal static string Contact_Outline {
            get {
                return ResourceManager.GetString("Contact_Outline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Police Office:.
        /// </summary>
        internal static string Contact_Police {
            get {
                return ResourceManager.GetString("Contact_Police", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thiqa Office:.
        /// </summary>
        internal static string Contact_Thiqa {
            get {
                return ResourceManager.GetString("Contact_Thiqa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contacts.
        /// </summary>
        internal static string Contact_Title {
            get {
                return ResourceManager.GetString("Contact_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string DLG_Error {
            get {
                return ResourceManager.GetString("DLG_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        internal static string Doctors_All {
            get {
                return ResourceManager.GetString("Doctors_All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Result.
        /// </summary>
        internal static string Doctors_Title {
            get {
                return ResourceManager.GetString("Doctors_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Events.
        /// </summary>
        internal static string Event_Title {
            get {
                return ResourceManager.GetString("Event_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        internal static string EventDetail_Date {
            get {
                return ResourceManager.GetString("EventDetail_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event details.
        /// </summary>
        internal static string EventDetail_Title {
            get {
                return ResourceManager.GetString("EventDetail_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FAQ item.
        /// </summary>
        internal static string Faq_Title {
            get {
                return ResourceManager.GetString("Faq_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FAQ.
        /// </summary>
        internal static string FaqList_Title {
            get {
                return ResourceManager.GetString("FaqList_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insurance details.
        /// </summary>
        internal static string Insurance_Title {
            get {
                return ResourceManager.GetString("Insurance_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insurances.
        /// </summary>
        internal static string InsuranceList_Title {
            get {
                return ResourceManager.GetString("InsuranceList_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Al-Ain Hospital.
        /// </summary>
        internal static string Location_Pin {
            get {
                return ResourceManager.GetString("Location_Pin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find us.
        /// </summary>
        internal static string Location_Title {
            get {
                return ResourceManager.GetString("Location_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main Page.
        /// </summary>
        internal static string MainPage_Title {
            get {
                return ResourceManager.GetString("MainPage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact.
        /// </summary>
        internal static string MasterPage_FOOTER_Contact {
            get {
                return ResourceManager.GetString("MasterPage_FOOTER_Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INFO.
        /// </summary>
        internal static string MasterPage_FOOTER_Info {
            get {
                return ResourceManager.GetString("MasterPage_FOOTER_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        internal static string MasterPage_FOOTER_Location {
            get {
                return ResourceManager.GetString("MasterPage_FOOTER_Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to e-Services.
        /// </summary>
        internal static string MasterPage_FOOTER_Service {
            get {
                return ResourceManager.GetString("MasterPage_FOOTER_Service", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading . . ..
        /// </summary>
        internal static string MasterPage_Loading {
            get {
                return ResourceManager.GetString("MasterPage_Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu.
        /// </summary>
        internal static string MasterPage_Menu {
            get {
                return ResourceManager.GetString("MasterPage_Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attach.
        /// </summary>
        internal static string NewFile_Attach {
            get {
                return ResourceManager.GetString("NewFile_Attach", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emirates ID.
        /// </summary>
        internal static string NewFile_Emirate {
            get {
                return ResourceManager.GetString("NewFile_Emirate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note:.
        /// </summary>
        internal static string NewFile_Head {
            get {
                return ResourceManager.GetString("NewFile_Head", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string NewFile_Name {
            get {
                return ResourceManager.GetString("NewFile_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        internal static string NewFile_Submit {
            get {
                return ResourceManager.GetString("NewFile_Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please fill the form.
        /// </summary>
        internal static string NewFile_SUBMIT_DLG_Msg {
            get {
                return ResourceManager.GetString("NewFile_SUBMIT_DLG_Msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thiqa.
        /// </summary>
        internal static string NewFile_Thiqa {
            get {
                return ResourceManager.GetString("NewFile_Thiqa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New File.
        /// </summary>
        internal static string NewFile_Title {
            get {
                return ResourceManager.GetString("NewFile_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload.
        /// </summary>
        internal static string NewFile_Upload {
            get {
                return ResourceManager.GetString("NewFile_Upload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date:.
        /// </summary>
        internal static string News_Date {
            get {
                return ResourceManager.GetString("News_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to News details.
        /// </summary>
        internal static string News_Title {
            get {
                return ResourceManager.GetString("News_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to News.
        /// </summary>
        internal static string NewsList_Title {
            get {
                return ResourceManager.GetString("NewsList_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seems like our connection dropped or timed out. Please try again..
        /// </summary>
        internal static string NO_INTERNET_MSG {
            get {
                return ResourceManager.GetString("NO_INTERNET_MSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bio:.
        /// </summary>
        internal static string Profile_Bio {
            get {
                return ResourceManager.GetString("Profile_Bio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language:.
        /// </summary>
        internal static string Profile_Language {
            get {
                return ResourceManager.GetString("Profile_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qualifications:.
        /// </summary>
        internal static string Profile_Qual {
            get {
                return ResourceManager.GetString("Profile_Qual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doctor profile.
        /// </summary>
        internal static string Profile_Title {
            get {
                return ResourceManager.GetString("Profile_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Number.
        /// </summary>
        internal static string RegCme_Contact {
            get {
                return ResourceManager.GetString("RegCme_Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string RegCme_Email {
            get {
                return ResourceManager.GetString("RegCme_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employer.
        /// </summary>
        internal static string RegCme_Employer {
            get {
                return ResourceManager.GetString("RegCme_Employer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string RegCme_Name {
            get {
                return ResourceManager.GetString("RegCme_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        internal static string RegCme_Register {
            get {
                return ResourceManager.GetString("RegCme_Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        internal static string RegCme_Reset {
            get {
                return ResourceManager.GetString("RegCme_Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        internal static string RegCme_Title {
            get {
                return ResourceManager.GetString("RegCme_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please fill the form. All fields are required.
        /// </summary>
        internal static string SearchAppointment_DLG_Msg {
            get {
                return ResourceManager.GetString("SearchAppointment_DLG_Msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emirates ID:.
        /// </summary>
        internal static string SearchAppointment_Emirate {
            get {
                return ResourceManager.GetString("SearchAppointment_Emirate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MRN:.
        /// </summary>
        internal static string SearchAppointment_MRN {
            get {
                return ResourceManager.GetString("SearchAppointment_MRN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        internal static string SearchAppointment_Reset {
            get {
                return ResourceManager.GetString("SearchAppointment_Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string SearchAppointment_Search {
            get {
                return ResourceManager.GetString("SearchAppointment_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find Doctor.
        /// </summary>
        internal static string SearchDoctor_Find {
            get {
                return ResourceManager.GetString("SearchDoctor_Find", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string SearchDoctor_Search {
            get {
                return ResourceManager.GetString("SearchDoctor_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specialties.
        /// </summary>
        internal static string SearchDoctor_Spec {
            get {
                return ResourceManager.GetString("SearchDoctor_Spec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find a Doctor.
        /// </summary>
        internal static string SearchDoctor_Title {
            get {
                return ResourceManager.GetString("SearchDoctor_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I agree.
        /// </summary>
        internal static string TermsPage_Agree {
            get {
                return ResourceManager.GetString("TermsPage_Agree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you for submitting the File, you will be contacted shortly.
        /// </summary>
        internal static string TermsPage_DLG_Msg {
            get {
                return ResourceManager.GetString("TermsPage_DLG_Msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File has been sent!.
        /// </summary>
        internal static string TermsPage_DLG_Title {
            get {
                return ResourceManager.GetString("TermsPage_DLG_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terms goes here.
        /// </summary>
        internal static string TermsPage_TermsText {
            get {
                return ResourceManager.GetString("TermsPage_TermsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Health Tip.
        /// </summary>
        internal static string Tips_Title {
            get {
                return ResourceManager.GetString("Tips_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Appoin..
        /// </summary>
        internal static string View_Appointment {
            get {
                return ResourceManager.GetString("View_Appointment", resourceCulture);
            }
        }
    }
}
