// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace HealthDemo {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources_ar {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources_ar() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("HealthDemo.AppResources_ar", typeof(AppResources_ar).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string Appointment_FORM_Submit {
            get {
                return ResourceManager.GetString("Appointment_FORM_Submit", resourceCulture);
            }
        }
        
        internal static string CME_Title {
            get {
                return ResourceManager.GetString("CME_Title", resourceCulture);
            }
        }
        
        internal static string NewFile_Emirate {
            get {
                return ResourceManager.GetString("NewFile_Emirate", resourceCulture);
            }
        }
        
        internal static string RegCme_Title {
            get {
                return ResourceManager.GetString("RegCme_Title", resourceCulture);
            }
        }
        
        internal static string CME_Head {
            get {
                return ResourceManager.GetString("CME_Head", resourceCulture);
            }
        }
        
        internal static string NewFile_Thiqa {
            get {
                return ResourceManager.GetString("NewFile_Thiqa", resourceCulture);
            }
        }
        
        internal static string Doctors_All {
            get {
                return ResourceManager.GetString("Doctors_All", resourceCulture);
            }
        }
        
        internal static string SearchAppointment_Emirate {
            get {
                return ResourceManager.GetString("SearchAppointment_Emirate", resourceCulture);
            }
        }
        
        internal static string MasterPage_FOOTER_Info {
            get {
                return ResourceManager.GetString("MasterPage_FOOTER_Info", resourceCulture);
            }
        }
        
        internal static string SearchDoctor_Find {
            get {
                return ResourceManager.GetString("SearchDoctor_Find", resourceCulture);
            }
        }
        
        internal static string NewFile_SUBMIT_DLG_Msg {
            get {
                return ResourceManager.GetString("NewFile_SUBMIT_DLG_Msg", resourceCulture);
            }
        }
        
        internal static string Appointment_FORM_Email {
            get {
                return ResourceManager.GetString("Appointment_FORM_Email", resourceCulture);
            }
        }
        
        internal static string MasterPage_Loading {
            get {
                return ResourceManager.GetString("MasterPage_Loading", resourceCulture);
            }
        }
        
        internal static string Category_Title {
            get {
                return ResourceManager.GetString("Category_Title", resourceCulture);
            }
        }
        
        internal static string Contact_Thiqa {
            get {
                return ResourceManager.GetString("Contact_Thiqa", resourceCulture);
            }
        }
        
        internal static string Tips_Title {
            get {
                return ResourceManager.GetString("Tips_Title", resourceCulture);
            }
        }
        
        internal static string Insurance_Title {
            get {
                return ResourceManager.GetString("Insurance_Title", resourceCulture);
            }
        }
        
        internal static string News_Title {
            get {
                return ResourceManager.GetString("News_Title", resourceCulture);
            }
        }
        
        internal static string FaqList_Title {
            get {
                return ResourceManager.GetString("FaqList_Title", resourceCulture);
            }
        }
        
        internal static string Contact_Content {
            get {
                return ResourceManager.GetString("Contact_Content", resourceCulture);
            }
        }
        
        internal static string SearchAppointment_MRN {
            get {
                return ResourceManager.GetString("SearchAppointment_MRN", resourceCulture);
            }
        }
        
        internal static string RegCme_Email {
            get {
                return ResourceManager.GetString("RegCme_Email", resourceCulture);
            }
        }
        
        internal static string Appointment_Title {
            get {
                return ResourceManager.GetString("Appointment_Title", resourceCulture);
            }
        }
        
        internal static string TermsPage_Agree {
            get {
                return ResourceManager.GetString("TermsPage_Agree", resourceCulture);
            }
        }
        
        internal static string Appointment_FORM_Name {
            get {
                return ResourceManager.GetString("Appointment_FORM_Name", resourceCulture);
            }
        }
        
        internal static string NewFile_Attach {
            get {
                return ResourceManager.GetString("NewFile_Attach", resourceCulture);
            }
        }
        
        internal static string MasterPage_FOOTER_Contact {
            get {
                return ResourceManager.GetString("MasterPage_FOOTER_Contact", resourceCulture);
            }
        }
        
        internal static string NewFile_Title {
            get {
                return ResourceManager.GetString("NewFile_Title", resourceCulture);
            }
        }
        
        internal static string TermsPage_DLG_Title {
            get {
                return ResourceManager.GetString("TermsPage_DLG_Title", resourceCulture);
            }
        }
        
        internal static string CME_Venue {
            get {
                return ResourceManager.GetString("CME_Venue", resourceCulture);
            }
        }
        
        internal static string Profile_Qual {
            get {
                return ResourceManager.GetString("Profile_Qual", resourceCulture);
            }
        }
        
        internal static string InsuranceList_Title {
            get {
                return ResourceManager.GetString("InsuranceList_Title", resourceCulture);
            }
        }
        
        internal static string CME_CreditHour {
            get {
                return ResourceManager.GetString("CME_CreditHour", resourceCulture);
            }
        }
        
        internal static string Contact_Title {
            get {
                return ResourceManager.GetString("Contact_Title", resourceCulture);
            }
        }
        
        internal static string RegCme_Employer {
            get {
                return ResourceManager.GetString("RegCme_Employer", resourceCulture);
            }
        }
        
        internal static string Calendar_Title {
            get {
                return ResourceManager.GetString("Calendar_Title", resourceCulture);
            }
        }
        
        internal static string Profile_Title {
            get {
                return ResourceManager.GetString("Profile_Title", resourceCulture);
            }
        }
        
        internal static string Appointment_SUBMIT_DLG_Msg {
            get {
                return ResourceManager.GetString("Appointment_SUBMIT_DLG_Msg", resourceCulture);
            }
        }
        
        internal static string News_Date {
            get {
                return ResourceManager.GetString("News_Date", resourceCulture);
            }
        }
        
        internal static string Location_Pin {
            get {
                return ResourceManager.GetString("Location_Pin", resourceCulture);
            }
        }
        
        internal static string Contact_Police {
            get {
                return ResourceManager.GetString("Contact_Police", resourceCulture);
            }
        }
        
        internal static string DLG_Error {
            get {
                return ResourceManager.GetString("DLG_Error", resourceCulture);
            }
        }
        
        internal static string Faq_Title {
            get {
                return ResourceManager.GetString("Faq_Title", resourceCulture);
            }
        }
        
        internal static string Contact_Ambulance {
            get {
                return ResourceManager.GetString("Contact_Ambulance", resourceCulture);
            }
        }
        
        internal static string NewFile_Head {
            get {
                return ResourceManager.GetString("NewFile_Head", resourceCulture);
            }
        }
        
        internal static string Appointment_SEND_DLG_Msg {
            get {
                return ResourceManager.GetString("Appointment_SEND_DLG_Msg", resourceCulture);
            }
        }
        
        internal static string SearchDoctor_Title {
            get {
                return ResourceManager.GetString("SearchDoctor_Title", resourceCulture);
            }
        }
        
        internal static string Contact_Outline {
            get {
                return ResourceManager.GetString("Contact_Outline", resourceCulture);
            }
        }
        
        internal static string NewFile_Submit {
            get {
                return ResourceManager.GetString("NewFile_Submit", resourceCulture);
            }
        }
        
        internal static string Contact_CallCenter {
            get {
                return ResourceManager.GetString("Contact_CallCenter", resourceCulture);
            }
        }
        
        internal static string Appointment_FORM_Clinical {
            get {
                return ResourceManager.GetString("Appointment_FORM_Clinical", resourceCulture);
            }
        }
        
        internal static string About_Content {
            get {
                return ResourceManager.GetString("About_Content", resourceCulture);
            }
        }
        
        internal static string Profile_Language {
            get {
                return ResourceManager.GetString("Profile_Language", resourceCulture);
            }
        }
        
        internal static string CME_DT {
            get {
                return ResourceManager.GetString("CME_DT", resourceCulture);
            }
        }
        
        internal static string About_HeaderTitle {
            get {
                return ResourceManager.GetString("About_HeaderTitle", resourceCulture);
            }
        }
        
        internal static string Profile_Bio {
            get {
                return ResourceManager.GetString("Profile_Bio", resourceCulture);
            }
        }
        
        internal static string RegCme_Contact {
            get {
                return ResourceManager.GetString("RegCme_Contact", resourceCulture);
            }
        }
        
        internal static string TermsPage_DLG_Msg {
            get {
                return ResourceManager.GetString("TermsPage_DLG_Msg", resourceCulture);
            }
        }
        
        internal static string Appointment_SUBMIT_DLG_Title {
            get {
                return ResourceManager.GetString("Appointment_SUBMIT_DLG_Title", resourceCulture);
            }
        }
        
        internal static string EventDetail_Title {
            get {
                return ResourceManager.GetString("EventDetail_Title", resourceCulture);
            }
        }
        
        internal static string CME_Register {
            get {
                return ResourceManager.GetString("CME_Register", resourceCulture);
            }
        }
        
        internal static string MasterPage_FOOTER_Service {
            get {
                return ResourceManager.GetString("MasterPage_FOOTER_Service", resourceCulture);
            }
        }
        
        internal static string SearchDoctor_Search {
            get {
                return ResourceManager.GetString("SearchDoctor_Search", resourceCulture);
            }
        }
        
        internal static string Appointment_FORM_MRN {
            get {
                return ResourceManager.GetString("Appointment_FORM_MRN", resourceCulture);
            }
        }
        
        internal static string Cme_REGISTER_DLG_Msg {
            get {
                return ResourceManager.GetString("Cme_REGISTER_DLG_Msg", resourceCulture);
            }
        }
        
        internal static string EventDetail_Date {
            get {
                return ResourceManager.GetString("EventDetail_Date", resourceCulture);
            }
        }
        
        internal static string Doctors_Title {
            get {
                return ResourceManager.GetString("Doctors_Title", resourceCulture);
            }
        }
        
        internal static string Appointment_FORM_Referral {
            get {
                return ResourceManager.GetString("Appointment_FORM_Referral", resourceCulture);
            }
        }
        
        internal static string SearchAppointment_Reset {
            get {
                return ResourceManager.GetString("SearchAppointment_Reset", resourceCulture);
            }
        }
        
        internal static string Appointment_FORM_Thiqa {
            get {
                return ResourceManager.GetString("Appointment_FORM_Thiqa", resourceCulture);
            }
        }
        
        internal static string NewFile_Name {
            get {
                return ResourceManager.GetString("NewFile_Name", resourceCulture);
            }
        }
        
        internal static string MasterPage_Menu {
            get {
                return ResourceManager.GetString("MasterPage_Menu", resourceCulture);
            }
        }
        
        internal static string SearchAppointment_Search {
            get {
                return ResourceManager.GetString("SearchAppointment_Search", resourceCulture);
            }
        }
        
        internal static string AppointmentResult_Time {
            get {
                return ResourceManager.GetString("AppointmentResult_Time", resourceCulture);
            }
        }
        
        internal static string SearchDoctor_Spec {
            get {
                return ResourceManager.GetString("SearchDoctor_Spec", resourceCulture);
            }
        }
        
        internal static string CME_Description {
            get {
                return ResourceManager.GetString("CME_Description", resourceCulture);
            }
        }
        
        internal static string MainPage_Title {
            get {
                return ResourceManager.GetString("MainPage_Title", resourceCulture);
            }
        }
        
        internal static string RegCme_Name {
            get {
                return ResourceManager.GetString("RegCme_Name", resourceCulture);
            }
        }
        
        internal static string RegCme_Register {
            get {
                return ResourceManager.GetString("RegCme_Register", resourceCulture);
            }
        }
        
        internal static string Event_Title {
            get {
                return ResourceManager.GetString("Event_Title", resourceCulture);
            }
        }
        
        internal static string NewFile_Upload {
            get {
                return ResourceManager.GetString("NewFile_Upload", resourceCulture);
            }
        }
        
        internal static string Appointment_FORM_Phone {
            get {
                return ResourceManager.GetString("Appointment_FORM_Phone", resourceCulture);
            }
        }
        
        internal static string SearchAppointment_DLG_Msg {
            get {
                return ResourceManager.GetString("SearchAppointment_DLG_Msg", resourceCulture);
            }
        }
        
        internal static string CME_Speaker {
            get {
                return ResourceManager.GetString("CME_Speaker", resourceCulture);
            }
        }
        
        internal static string View_Appointment {
            get {
                return ResourceManager.GetString("View_Appointment", resourceCulture);
            }
        }
        
        internal static string RegCme_Reset {
            get {
                return ResourceManager.GetString("RegCme_Reset", resourceCulture);
            }
        }
        
        internal static string Appointment_FORM_Head {
            get {
                return ResourceManager.GetString("Appointment_FORM_Head", resourceCulture);
            }
        }
        
        internal static string Appointment_FORM_ID {
            get {
                return ResourceManager.GetString("Appointment_FORM_ID", resourceCulture);
            }
        }
        
        internal static string NewsList_Title {
            get {
                return ResourceManager.GetString("NewsList_Title", resourceCulture);
            }
        }
        
        internal static string MasterPage_FOOTER_Location {
            get {
                return ResourceManager.GetString("MasterPage_FOOTER_Location", resourceCulture);
            }
        }
        
        internal static string AppointmentResult_Date {
            get {
                return ResourceManager.GetString("AppointmentResult_Date", resourceCulture);
            }
        }
        
        internal static string Location_Title {
            get {
                return ResourceManager.GetString("Location_Title", resourceCulture);
            }
        }
        
        internal static string NO_INTERNET_MSG {
            get {
                return ResourceManager.GetString("NO_INTERNET_MSG", resourceCulture);
            }
        }
        
        internal static string TermsPage_TermsText {
            get {
                return ResourceManager.GetString("TermsPage_TermsText", resourceCulture);
            }
        }
    }
}
